---
- name: Update apt cache
  apt:
    update_cache: true

- name: Install nginx packages
  apt:
    pkg:
      - nginx
      - certbot

- name: Configure Certbot
  copy:
    src: certbot-cli.ini
    dest: /etc/letsencrypt/cli.ini
    mode: '644'

- name: create nginx SSL directory
  file:
    path: /etc/nginx/ssl
    owner: root
    group: root
    mode: '700'
    state: directory

- name: Generate DH parameters
  shell: openssl dhparam -writerand - 4096 > /etc/ssl/dhparam.pem
  args:
    chdir: /etc/nginx/ssl
    creates: /etc/ssl/dhparam.pem

- name: Register Let's Encrypt Staging Account
  command: certbot register --email {{ letsencrypt_email }} --agree-tos -n --staging
  args:
    creates: /etc/letsencrypt/accounts
  when:
    letsencrypt_staging|bool and
    letsencrypt_enable|bool


- name: Register Let's Encrypt Production Account
  command: certbot register --email {{ letsencrypt_email }} --agree-tos -n
  args:
    creates: /etc/letsencrypt/accounts
  when:
    not letsencrypt_staging|bool and
    letsencrypt_enable|bool

- name: Generate Self Signed
  include_tasks: ssl_selfsigned.yml
  when: not letsencrypt_enable|bool

- name: Create nginx project config directory
  file:
    path: /etc/nginx/project-sites
    owner: root
    group: root
    mode: '755'
    state: directory

- name: Copy nginx template to /etc/nginx/project-sites/template
  copy:
    src: template
    dest: /etc/nginx/project-sites/template
    mode: '644'

- name: Reload nginx
  systemd:
    state: reloaded
    name: nginx
