---
- hosts: mailman
  gather_facts: no
  roles:
    - proxmox-provision-vm

- hosts: mailman
  become: yes
  roles:
    - common
    - install-mailman
    - firewall
    - unattended-upgrades # Unattended-Upgrades role from https://github.com/jnv/ansible-role-unattended-upgrades
    - harden-ssh # harden-ssh from https://github.com/jlu5/ansible-common
