---
- name: Update apt cache
  apt:
    update_cache: true

- name: Install nginx packages
  apt:
    pkg:
      - nginx
      - certbot

- name: create nginx SSL directory
  file:
    path: /etc/nginx/ssl
    owner: root
    group: root
    mode: '700'
    state: directory

- name: Generate DH parameters
  shell: openssl dhparam -writerand - 4096 > /etc/ssl/dhparam.pem
  args:
    chdir: /etc/nginx/ssl
    creates: /etc/ssl/dhparam.pem

- name: Register Let's Encrypt Staging Account
  command: certbot register --email {{ letsencrypt_email }} --agree-tos -n --staging
  args:
    creates: /etc/letsencrypt/accounts
  when: staging_env

- name: Register Let's Encrypt Production Account
  command: certbot register --email {{ letsencrypt_email }} --agree-tos -n
  args:
    creates: /etc/letsencrypt/accounts
  when: not staging_env

- name: Reload nginx
  systemd:
    state: reloaded
    name: nginx