---
- hosts: local
  roles:
    - proxmox-provision-vm

- hosts: webserver
  become: yes
  roles:
    - common
    - install-nginx
    - firewall
    - unattended-upgrades # Unattended-Upgrades role from https://github.com/jnv/ansible-role-unattended-upgrades
    - harden-ssh # harden-ssh from https://github.com/jlu5/ansible-common