---
- hosts: local
  roles:
    - proxmox-provision-vm

- hosts: webserver
  become: yes
  roles:
    - common
    - install-nginx
    - install-ipfs
    - install-hypercore
    - install-api
    - firewall
