---
- name: Install postfix packages
  apt:
    pkg:
      - postfix

- name: Set Postfix option type as internet site
  debconf: 
    name=postfix
    question="postfix/main_mailer_type"
    value="'Internet Site'"
    vtype="string"
