---
- name: Update apt cache
  apt:
    update_cache: true

- name: Install Apache2 packages
  apt:
    pkg:
      - apache2
      - certbot

- name: Register Let's Encrypt Production Account
  command: certbot register --email {{ letsencrypt_email }} --agree-tos -n
  args:
    creates: /etc/letsencrypt/accounts

- name: Get Let's Encrypt Cert
  command: certbot certonly --webroot -w /var/www/html/ -d {{ site_hostname }} -d {{ site_hostname }} --rsa-key-size 4096
  args:
    creates: /etc/letsencrypt/live/{{ site_hostname }}/fullchain.pem
