#!/bin/bash
set -e

# Staging?
staging=1

for project in $(cat /home/press/.distributed-press/config2.json | jq -r '.activeProjects[] .projectDomain') # change to config.json in prod
do
	if [ $staging -eq 1 ]
	then
		echo "SCRIPT IN STAGING MODE"
	fi
	echo "Project: $project"
	echo "NGINX webroot: /home/press/.distributed-press/tmp/$project/www/" # using tmp instead of data for testing
	if [ ! -L "/etc/nginx/sites-enabled/$project" ]
	then
		echo "Getting cert for $project"
		if [ $staging -eq 1 ]
		then
			certbot certonly --webroot -w /var/www/html/ -d $project -d api.$project --rsa-key-size 4096 --staging
		else
			certbot certonly --webroot -w /var/www/html/ -d $project -d api.$project --rsa-key-size 4096
		fi
		echo "Copying template to /etc/nginx/project-sites/$project"
		cp /etc/nginx/project-sites/template /etc/nginx/project-sites/$project
		echo "Editing /etc/nginx/project-sites/$project"
		sed -i -e "s/__project__/$project/g" /etc/nginx/project-sites/$project
		echo "Enabling $project NGINX config"
		ln -s /etc/nginx/project-sites/$project /etc/nginx/sites-enabled/$project
		echo "Reloading NGINX"
		systemctl reload nginx
	else
		echo "Project: $project already configured"
	fi
done
echo "All done"
exit 0
